### ISSUE TITLE
add_card error

### ISSUE THREAD

**Issue by sonicpieman** [fsahli/music-cards#5]
This is the error I receive when I run add_card.py. Anyone else getting this?

add_card.py
Traceback (most recent call last):
  File "add_card.py", line 5, in <module>
    cardList = CardList()
  File "/root/CardList.py", line 8, in __init__
    self.cardList = self.readList()
  File "/root/CardList.py", line 11, in readList
    with open(self.path + '/cardList.csv', mode='r') as infile:

**Comment by fsahli** [comment]
I am pretty sure you didn't paste the entire error, but try executing the command "touch cardList.csv"
This will create an empty file. Also, check the comments of the blog post, there are ton of solutions to problems like this: https://fsahli.wordpress.com/2015/11/02/music-cards-rfid-cards-spotify-raspberry-pi/
